name : 'Terraform'

on:
  workflow_dispatch:
    # inputs:
    #   region-value:
    #     # Friendly description to be shown in the UI instead of 'name'
    #     description: 'enter region'
    #     # Default value if no value is explicitly provided
    #     # default: ''u-east-1
    #     # Input has to be provided for the workflow to run
    #     required: true
  push:
    branches: [ "main" ]


jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest

    

    defaults:
      run:
        working-directory: ./example/

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:      ${{ secrets.AWS_SESSION_TOKEN }} add token in secrets

          aws-region: ap-south-1                      #${{ github.event.inputs.region-value }}      

      - name: Terraform Init
        id: init
        run: terraform init
         
      
      
      - name: Terraform validate
        id: validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -lock=false

      - name: Terraform Apply
        id: apply
        run:  terraform apply -auto-approve